name: Docker Image CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Short commit hash
        run: echo "TC_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USER }}/tech-challenge-queue-service:${{ env.TC_IMAGE_TAG }} -f devops/docker/Dockerfile .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/tech-challenge-queue-service:${{ env.TC_IMAGE_TAG }}